environments:
  development:

--- 

repositories:
  - name: prometheus-community 
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus
    chart: prometheus-community/prometheus
    namespace: monitoring
    values: 
      - alertmanager:
          enabled: false
        kube-state-metrics:
          enabled: false
        prometheus-node-exporter:
          enabled: false
        prometheus-pushgateway:
          enabled: false

